language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: DIZ2pHDWgkc8yHXsZ5d0y1021M65upmJZm9vTv3GmkvbDT7b7dtDXwcu1VmSSwWP58uO/tdBgYf/CSW2dO1mCeRhLma9onmmCi6eGHY+CeaS6YtZ4QkSeM1JL+Yj9cS6oZBLyRPUBSMpGoGm67571cY/NchTwSaxrt9ERtcR46U=
  on:
    all_branches: true
    tags: true
    repo: bendrucker/sinon-as-promised
